//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFbasEDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT_CLIENT
    {
        public int EC_ID { get; set; }
        public int EC_C { get; set; }
        public int EC_E { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual EVENT EVENT { get; set; }
    }
}
