//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFbasEDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EVENT()
        {
            this.EVENT_CLIENT = new HashSet<EVENT_CLIENT>();
        }
    
        public int E_ID { get; set; }
        public string E_TITLE { get; set; }
        public Nullable<System.DateTime> E_DATE { get; set; }
        public string E_VENUE { get; set; }
        public Nullable<double> E_ENTRANCE_PRICE { get; set; }
        public Nullable<double> E_RECEIPTS { get; set; }
        public Nullable<int> E_SG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENT_CLIENT> EVENT_CLIENT { get; set; }
        public virtual STATUS STATUS { get; set; }
    }
}
