//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFbasEDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LECTURE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LECTURE()
        {
            this.STUDENT_ON_LECTURE = new HashSet<STUDENT_ON_LECTURE>();
        }
    
        public int L_ID { get; set; }
        public int L_LC { get; set; }
        public Nullable<int> L_CL { get; set; }
        public string L_TOPIC { get; set; }
        public Nullable<System.DateTime> L_DATE { get; set; }
    
        public virtual COURSE_OF_LECTURE COURSE_OF_LECTURE { get; set; }
        public virtual LECTURER LECTURER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_ON_LECTURE> STUDENT_ON_LECTURE { get; set; }
    }
}
