//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFbasEDataEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FFbasE_New_EF : DbContext
    {
        public FFbasE_New_EF()
            : base("name=FFbasE_New_EF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENT> CLIENT { get; set; }
        public virtual DbSet<COURSE_OF_LECTURE> COURSE_OF_LECTURE { get; set; }
        public virtual DbSet<EVENT> EVENT { get; set; }
        public virtual DbSet<EVENT_CLIENT> EVENT_CLIENT { get; set; }
        public virtual DbSet<LECTURE> LECTURE { get; set; }
        public virtual DbSet<LECTURER> LECTURER { get; set; }
        public virtual DbSet<STATUS> STATUS { get; set; }
        public virtual DbSet<STUDENT> STUDENT { get; set; }
        public virtual DbSet<STUDENT_ON_LECTURE> STUDENT_ON_LECTURE { get; set; }
    }
}
