//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFbasEDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_ON_LECTURE
    {
        public int SL_ID { get; set; }
        public int SL_S { get; set; }
        public int SL_L { get; set; }
        public Nullable<bool> SL_PRESENCE { get; set; }
    
        public virtual LECTURE LECTURE { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
