//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFbasEDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT()
        {
            this.STUDENT_ON_LECTURE = new HashSet<STUDENT_ON_LECTURE>();
        }
    
        public int S_ID { get; set; }
        public int S_C { get; set; }
        public int S_CL { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual COURSE_OF_LECTURE COURSE_OF_LECTURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_ON_LECTURE> STUDENT_ON_LECTURE { get; set; }
    }
}
